# helm-infostrateg/values.yaml

worker:
  tag: "74cd52a4dd1591c45cdd28e5e61e3979788f9da9"
  image: ghcr.io/wojtekm990/ml-worker
  replicas: 1

api:
  tag: "74cd52a4dd1591c45cdd28e5e61e3979788f9da9"
  image: ghcr.io/wojtekm990/video-api

dashboard:
  tag: "74cd52a4dd1591c45cdd28e5e61e3979788f9da9"
  image: ghcr.io/wojtekm990/ml-dashboard
  replicas: 1

database:
  MYSQL_DB_PORT: 3306

spark:
  tag: "latest"
