# helm-infostrateg/values.yaml

worker:
  tag: "0e8f5645c469b400678166d417631d5a703e25e2"
  image: ghcr.io/wojtekm990/ml-worker
  replicas: 1

api:
  tag: "0e8f5645c469b400678166d417631d5a703e25e2"
  image: ghcr.io/wojtekm990/video-api

dashboard:
  image: ml-dashboard
  tag: "v1"

database:
  MYSQL_DB_PORT: 3306