apiVersion: v1
kind: Service
metadata:
  name: ml-service
spec:
  selector:
    app: image-classifier     # Service szuka Podów z tą etykietą
  ports:
    - protocol: TCP
      port: 80                # Na tym porcie Service słucha wewnątrz klastra
      targetPort: 8080        # Tu Twój model (gdyby miał API) by odbierał ruch
  type: LoadBalancer          # Dzięki temu Docker Desktop wystawi to na Twój komputer